In [1]:
import numpy as np

mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
arr=np.array(mat)
#per accedere usiamo gli indici in ordine decrescente, cioè dall'aarray, a ciò che c'è dentro
print(arr[1,4])



9


In [11]:
import math

x=int(input("inserisci un numero: "))

print(math.sin(x))
print(math.cos(x))
print(math.factorial(x))

print(math.pi)

inserisci un numero:  5


-0.9589242746631385
0.28366218546322625
120
3.141592653589793


In [12]:
#gradi angolo pi
math.degrees(math.pi) 


180.0

In [13]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



Esercizio
L'azienda Object SpA ha creato una lista
di quanti oggetti ha venduto ogni mese nell'ultimo anno:

lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

trasformiamola in un
array NumPy
(casting): lst = np.array(lst) 
e rispondiamo alle domande del CEO della Object SpA:
• qual è stata la vendita massima mensile? E quella minima?
• quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono?
• quali sono le vendite minori di 3000 oggetti? 
• in media quanti oggetti sono stati venduti al mese?

In [20]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

arr=np.array(lst)

# qual è stata la vendita massima mensile? E quella minima?
print(arr.max())
print(arr.min())


8150
1280


In [25]:
# quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono?
filtro=arr[arr > 4999]
print(filtro)
print(len(filtro))


[5500 7200 6410 8150 7100 5350]
6


In [27]:
# quali sono le vendite minori di 3000 oggetti? 
print(arr[arr<3000])



[2000 1280 1900 2500]


In [29]:
# in media quanti oggetti sono stati venduti al mese?

print(arr.mean())

4634.166666666667


In [42]:
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )
stip_rad=[]

for stipendio in stipendi:
    stip_rad.append(stipendio*2)
print(stip_rad)

[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]


In [43]:
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )

print(stipendi*2)

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
